name: Docker build
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      if: github.event.pull_request.merged
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
      
      - name: Build docker
        run: task docker:build
        working-directory: ./app
