name: 
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
      
      - name: Build docker
        run: task docker:build
        shell: bash
