name: Docker build
on:
  - workflow_run:
      workflows: ["Run NodeJS Test"]
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest
if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      if: github.event.pull_request.merged
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
      
      - name: Build docker
        run: task docker:build
        working-directory: ./app
