name: run-node-test
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - name: Run Test
        run: npm test
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
