name: Run NodeJS Test

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test